# crate name mapping (for use paths)
["模块路径"]
"tokio" = "tokio"
"async-std" = "async-std"
"futures" = "futures"
"async-trait" = "async-trait"

# internal identifier mapping (types, functions, etc.)
["标识符"]
# tokio
"main" = "main"
"spawn" = "spawn"
"await" = "await"
"select" = "select"
"delay_for" = "delay_for"
"interval" = "interval"
"sleep" = "sleep"
"spawn_blocking" = "spawn_blocking"
"channel" = "channel"
"oneshot" = "oneshot"
"broadcast" = "broadcast"

# async-std
"task" = "task"
"task::spawn_blocking" = "task::spawn_blocking"
"stream" = "stream"

# futures
"Future" = "Future"
"Sink" = "Sink"
"join" = "join"
"try_join" = "try_join"
"poll" = "poll"

# async-trait
"async_trait" = "async_trait"
