# क्रेट नाम मानचित्रण (use पथ के लिए)
["模块路径"]
"अनुरेखण" = "tracing"
"लॉग" = "log"
"पर्यावरण_लॉग" = "env_logger"
"अनुरेखण_ग्राहक" = "tracing-subscriber"

# आंतरिक पहचानकर्ता मानचित्रण (प्रकार, फ़ंक्शन आदि)
["标识符"]
# tracing
"अनुरेख" = "trace"
"डिबग_स्तर" = "debug"
"सूचना_स्तर" = "info"
"चेतावनी" = "warn"
"त्रुटि_स्तर" = "error"
"विस्तार_क्षेत्र" = "span"
"घटना" = "event"
"ग्राहक" = "subscriber"
"प्रारंभ_करो" = "init"

# log
"लॉग_स्तर" = "Level"
"लॉग_अभिलेख" = "Record"
"निर्माता" = "Builder"
"फ़िल्टर_लॉग" = "filter"

# tracing-subscriber
"प्रारूप_परत" = "fmt"
"जेसोन_परत" = "json"
"फ़िल्टर_परत" = "filter"
"रजिस्ट्री" = "registry"
